export enum Continent {
  EUROPE = 'EUROPE',
  ASIA = 'ASIA',
  EUROPE_ASIA = 'EUROPE_ASIA',
  NORTH_AMERICA = 'NORTH_AMERICA',
  SOUTH_AMERICA = 'SOUTH_AMERICA',
  AFRICA = 'AFRICA',
  AFRICA_ASIA = 'AFRICA_ASIA',
  OCEANIA = 'OCEANIA',
  ANTARCTICA = 'ANTARCTICA'
}